### ISSUE TITLE
[BUG] Copilot not taking off

### ISSUE THREAD

**Issue by arbadacarbaYK** [lnbits/streamer-copilot-extension#7]
First of all, i am shocked, that the fly swatter is not in 😂

With all thresholds set without a webhook it doesnt seem to work
![photo_2023-08-12_22-38-33](https://github.com/lnbits/copilot/assets/63317640/15e7f51f-f51f-4349-834a-a91434b0afed)

Btw without setting thresholds theres no indicator or message that its required. Should be an option as well

**Comment by talvasconcelos** [comment]
are you on latest version of copilot?

**Comment by arbadacarbaYK** [comment]
Was done on legend on 0.4.1. 
Rechecked on another instance with the latest version which works 🥳

The QR should be clickable to copy imo (lightning:lnurl) 

Also showing the bitcoin-price seems to be mandatory ? without its not saving/no message that its required still

**Comment by talvasconcelos** [comment]
0.4.3 version of copilot fixed it!

**Comment by arbadacarbaYK** [comment]
? what about the two other comments ??

**Comment by talvasconcelos** [comment]
@arbadacarbaYK 
`showing the bitcoin-price seems to be mandatory ?` - No, just tested only with name! Can you please test it further and give steps to reproduce?

The clickable QR would only work for you... the streamer! when you plug that into OBS, for example, there's no clicking, just a video being streamed!

**Comment by arbadacarbaYK** [comment]
Thanks for asking, will try to clarify. This is the default view 
<img width="741" alt="Bildschirmfoto 2023-08-17 um 23 24 50" src="https://github.com/lnbits/copilot/assets/63317640/fb19a4bb-288d-44a9-a6a5-fbf63b60bf16">

which will not work but not show why.

Only if you open the threshold (which shouldnt be mandatory) it shows the threshold amount mandatory
<img width="630" alt="Bildschirmfoto 2023-08-17 um 23 26 53" src="https://github.com/lnbits/copilot/assets/63317640/dc1c2573-b44e-43df-bdb9-94dd584c55a6">

And also this will not work (without currency conversion given) also without any message the button is not doing anything
<img width="595" alt="Bildschirmfoto 2023-08-17 um 23 29 13" src="https://github.com/lnbits/copilot/assets/63317640/87229017-e604-4455-9a2b-442708b48378">

**Comment by talvasconcelos** [comment]
you need to select the animation that triggers at a specific threshold.
when selecting one you need to set the other.

**Comment by arbadacarbaYK** [comment]
Yes, its mostly because the threshold combos are closed per default.
Nicer UX would be to show some messages or indicators on a higher level that show the threshold has to be opened at all.. min could be 0 or smth implied based on global settings we already have instead of needing a minimum value.. theres not really a mandatory need for a max also until you set a second threshold value which makes it second value -1 sat ..

**Comment by arbadacarbaYK** [comment]
Concerning the clickable QR it is enough if it works when opened with the LNbits own share-link from https://lnbits.yourdomain.com/copilot/cp/ best case with a lightning: prefix 😅
